services:
  - type: web
    name: bert-emotions-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_chatbot:app --host 0.0.0.0 --port 10000"
    pythonVersion: 3.10.12
